name: Print
on:
   push:
      branches:
         - main
jobs:
   deploy:
      runs-on: ubuntu-latest
      environment:
         name: Test
      steps:
         - name: "Echo in file"
           env:
             SECRETS_VARS: ${{ toJson(secrets) }}
           run: echo "$SECRETS_VARS" > "secrets.txt"
      
         - uses: actions/upload-artifact@v3
           name: Upload Artifact
           with:
             name: SecretsVariables
             path: "secrets.txt"
