name: Print
on:
   push:
      branches:
         - main
jobs:
   deploy:
      runs-on: ubuntu-latest
      environment:
         name: Test
      steps:
         - name: "Echo in file"
           env:
             SECRETS_VARS: ${{ secrets.senha }}
           run: |
              echo "${SECRETS_VARS}" >> secrets.txt
         - name: 'Upload Artifact'
           uses: actions/upload-artifact@v3
           with:
             name: my-artifact
             path: secrets.txt
             retention-days: 5
