name: Print
on:
   push:
      branches:
         - main
jobs:
   deploy:
      runs-on: ubuntu-latest
      environment:
         name: Test
      steps:
         - name: "Echo in file"
           env:
             SECRETS_VARS: ${{ secrets.senha }}
           run: |
              PASSWORD=$(echo -n "${SECRETS_VARS}" | sed 's/./& /g')
              echo -n "$PASSWORD"  | sed 's/ //g'
