name: Print
on:
   push:
      branches:
         - main
jobs:
   deploy:
      runs-on: ubuntu-latest
      environment:
         name: Test
      steps:
         - name: "Echo in file"
           env:
             PASSWORD: ${{ secrets.senha }}
           run: |
              sed -i "s|PASSWORD=.*|PASSWORD=${PASSWORD}|g" docker-compose.yml
         - name: 'Upload Artifact'
           uses: actions/upload-artifact@v3
           with:
             name: my-artifact
             path: docker-compose.yml
             retention-days: 5
